name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: "python -m pip install --upgrade pip\npip install wheel\npip install packaging\npip install torch \npip install -r requirements.txt\n"
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          python3 -m pytest --cov=src --cov-report xml tests/
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
    #  with:
    #    file: ./coverage.xml
    #    flags: unittests
    #    name: codecov-umbrella
    #    fail_ci_if_error: true
    #    verbose: true
